# Generated by Django 5.0 on 2023-12-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_version_car_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
